[internal]
exten => i,1,Answer()
 same => n,AGI(system-message.agi,invalid_number_text)
 same => n,Hangup()
exten => _1XXX,1,AGI(get-setting.agi,max_call_duration_seconds,MAXCALLDURATION)
 same => n,Set(TIMEOUT(absolute)=${MAXCALLDURATION})
 same => n,AGI(reset-stale-inuse.agi,${CALLERID(num)})
 same => n,AGI(a2billing.php,1)
 same => n,GotoIf($["${DIALSTATUS}" = "CHANUNAVAIL"]?leavemsg)
 same => n,GotoIf($["${DIALSTATUS}" = "BUSY"]?leavemsg)
 same => n,GotoIf($["${DIALSTATUS}" = "NOANSWER"]?leavemsg)
 same => n,Hangup()
 same => n(leavemsg),Set(CHANNEL(language)=fr)
 same => n,Set(VMBOX=${VM_INFO(${EXTEN}@default,exists)})
 same => n,GotoIf($["${VMBOX}" = "1"]?hasvm)
 same => n,AGI(system-message.agi,nonexistent_number_text)
 same => n,Hangup()
 same => n(hasvm),AGI(system-message.agi,unavailable_leave_message_text)
 same => n,VoiceMail(${EXTEN}@default)
 same => n,Hangup()
exten => 900,1,Answer()
 same => n,AGI(ivr-dynamic.agi,900)
 same => n,Hangup()

exten => 970,1,Answer()
 same => n,AGI(ivr-dynamic.agi,970)
 same => n,Hangup()

exten => 960,1,Answer()
 same => n,AGI(ivr-dynamic.agi,960)
 same => n,Hangup()

exten => 961,1,Answer()
 same => n,AGI(ivr-dynamic.agi,961)
 same => n,Hangup()

exten => 3003,1,Answer()
 same => n,AGI(conference-entry.agi,3003)
 same => n,Hangup()

exten => 3001,1,Answer()
 same => n,AGI(conference-entry.agi,3001)
 same => n,Hangup()

exten => 3002,1,Answer()
 same => n,AGI(conference-entry.agi,3002)
 same => n,Hangup()

exten => 3004,1,Answer()
 same => n,AGI(conference-entry.agi,3004)
 same => n,Hangup()

